### ISSUE TITLE
partition file

### ISSUE THREAD

**Issue by lindenozomi** [JSdoubleL/DISCO#2]
Hi,

is there an easy way to get a partition file for the concatenated alignment made by ca_disco.py?

best,
Linde

**Comment by JSdoubleL** [comment]
Hi Linde,

Thanks for reaching out! Currently there isn't an easy way to get a partition file. I will go ahead and look into implementing it.

Best,
James

**Comment by JSdoubleL** [comment]
Okay, I've gone ahead and implemented the ability to create a partition file with CA-DISCO. Let me know if you have any questions!

Best,
James
