### ISSUE TITLE
Section S1 & S2 of the Supplementary material?

### ISSUE THREAD

**Issue by goshng** [JSdoubleL/DISCO#4]
Hi,

I am unsure whether this is a good place to ask about the DISCO paper. I am trying to locate Sections S1 and S2 of the Supplementary material of the paper:

Willson J, Roddur MS, Liu B, Zaharias P, Warnow T. 2021. DISCO: Species Tree Inference using Multicopy Gene Family Tree Decomposition. Systematic Biology [Internet] 71:610–629. Available from: https://www.semanticscholar.org/paper/c2e21361ab0916cea8dee36891c6bc3c929c624d

I had a hard time locating tables in the Supplementary material as well. 

Anyway, the following is the excerpt where I am confused.

```
Experiment Overview
Full details (including software version numbers and commands necessary to reproduce the experiment) are provided in Sections S1 and S2 of the Supplementary material in the paper.
```

By the way, thank you for the great work, DISCO.

SangChul

**Comment by JSdoubleL** [comment]
Sorry for the delayed response. Here's a link to the supplementary materials: http://tandy.cs.illinois.edu/disco-suppl.pdf

Best,
James
